import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Layout from "@/components/Layout";


import profilePic from "../../public/images/profile/HeroImg.png";
import hero1 from "../../public/images/profile/heroimg1.png"
import hero2 from "../../public/images/profile/heroimg2.png"
import cloud from "../../public/images/assets/cloud.png"
import crown from "../../public/images/assets/crown.png"
import Cherrypops from "../../public/images/assets/Cherrypops_logo.png"


import AnimatedText from "@/components/AnimatedText";
import Link from "next/link";
import { LinkArrow } from "@/components/Icons";
import HireMe from "@/components/HireMe";
import lightBulb from '../../public/images/svgs/miscellaneous_icons_1.svg'
import TransitionEffect from "@/components/TransitionEffect";
import ProductEffective from "@/components/ProductEffective";
import Ingreadients from "@/components/ingredients"
import Instagram from "@/components/Instagram"
import Testimonials from "@/components/Testimonials";
import About from "@/components/About";
import TvCarousel from "@/components/TvCarousel";




// import Line from "../../public/images/assets/line.png"

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Cherrypops</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/assets/Cherrypops_logo.png" />
      </Head>
      <TransitionEffect />
      <main className="flex item-center text-dark w-full min-h-screen">
        <Layout className="pt-0 md:pt-16 sm:pt-8">
          <div className="flex items-center justify-between w-full lg:flex-col">

            <div className="w-1/2 md:w-full">
              <Image src={profilePic} alt="CB" className="w-full h-auto md:inline-block md:w-full dark:text-light"
                priority
                sizes="(max-width: 768px) 100vw,
              (max-width: 1200px) 50vw,
              50vw" />
            </div>
            <div className="w-1/2 flex flex-col items-center self-center lg:w-full lg:text-center
            ">
              <AnimatedText
                text="We treat Your Pets Right"
                className="!text-5xl !text-left 
                xl:!text-5xl lg:!text-center lg:!text-6xl md:text-xl sm:text-l md:mb-5"
              />

              {/* <p className="my-4 text-base font-medium md:text-small sm:text-xs">
                As a skilled full-stack developer, I am dedicated to turning
                ideas into innovative web applications. Explore my latest
                projects and articles, showcasing my expertise in React.js and
                web development.
              </p> */}


              <div className="flex items-start justify-around relative mt-10 lg:self-center md:mt-8 ">

                <Image src={cloud} alt="cloud" className="w-2/3 h-auto absolute tranform -rotate-12 top-[-120px] left-[-100px] md:top-[-60px] md:left-[-45px] lg:top-[-100px] lg:left-[-80px]" />

                <Image src={hero2} alt="CP" className="w-full h-auto tranform -rotate-12 lg:w-full lg:inline-block  md:inline-block md:w-full"
                  priority
                  sizes="(max-width: 768px) 100vw,
              (max-width: 1200px) 50vw,
              50vw" />

                <Image src={cloud} alt="cloud" className="w-2/3 h-auto absolute tranform rotate-12 top-[-120px] left-[250px] md:top-[-60px] md:left-[105px] md:w-2/3 lg:top-[-100px] lg:left-[200px]" />

                <Image src={hero1} alt="CP" className="w-full h-auto ml-[120px] tranform rotate-12 md:translate-x-0 lg:w-full md:inline-block md:w-full md:ml-6"
                  priority
                  sizes="(max-width: 768px) 100vw,
              (max-width: 1200px) 50vw,
              50vw" />
              </div>
            </div>
          </div>

          <TvCarousel />

          <ProductEffective />

          <About />
          <Ingreadients />


          {/* <Testimonials /> */}
          <Instagram />
        </Layout>

        {/* <div>
          <img src="/images/assets/wave.png" alt="Wave" />
        </div> */}
        <HireMe />


      </main>
    </>
  );
}
