import React, { useState, useEffect } from 'react';
import Link from 'next/link';
import { BsBagCheckFill } from 'react-icons/bs';


import { runFireworks } from '../../lib/utils.js';
import TransitionEffect from '@/components/TransitionEffect.js';
import Layout from '@/components/Layout.js';
import Head from 'next/head.js';

const Success = () => {
  
  useEffect(() => {

    runFireworks();
  }, []);

  return (
    <>
    <Head>
       <title>Success</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/assets/Cherrypops_logo.png" />
      </Head>
    <TransitionEffect />
    <Layout>
    <div className="success-wrapper">
      <div className="success">
        <p className="icon">
          <BsBagCheckFill />
        </p>
        <h2>Thank you for your order!</h2>
        <p className="email-msg">Check your email inbox for the receipt.</p>
        <p className="description">
          If you have any questions, please email
          <a className="email" href="mailto:order@example.com">
            order@example.com
          </a>
        </p>
        <Link href="/shop">
          <button type="button" width="300px" className="buttons1">
            Continue Shopping
          </button>
        </Link>
      </div>
    </div>
    </Layout>
      
    </>

  )
}

export default Success;