export const PLACE_ORDER_REQ = "PLACE_ORDER_REQ"
export const PLACE_ORDER_SUCCESS = "PLACE_ORDER_SUCCESS"
export const PLACE_ORDER_FAIL = "PLACE_ORDER_FAIL"
export const PLACE_ORDER_RESET = "PLACE_ORDER_RESET"

export const ORDER_PAYMENT_DETAIL_REQ = "ORDER_PAYMENT_DETAIL_REQ"
export const ORDER_PAYMENT_DETAIL_SUCCESS = "ORDER_PAYMENT_DETAIL_SUCCESS"
export const ORDER_PAYMENT_DETAIL_FAIL = "ORDER_PAYMENT_DETAIL_FAIL"